name = "aniflixx-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
AUTH_WORKER_URL = "https://aniflixx-auth.black-poetry-4fa5.workers.dev"
MEDIA_WORKER_URL = "https://aniflixx-media.black-poetry-4fa5.workers.dev"
CLOUDFLARE_STREAM_CUSTOMER_CODE = "jvg1dxngjkn57j9y"

# Secrets - Set these via command line:
# wrangler secret put CLOUDFLARE_ACCOUNT_ID
# wrangler secret put CLOUDFLARE_API_TOKEN

[[d1_databases]]
binding = "DB"
database_name = "aniflixx-main-db"
database_id = "2b5513fe-cf8c-4bb5-8872-5e85c38d5e54"

[[kv_namespaces]]
binding = "CACHE"
id = "213dae65137c472ba25b69159b3ca570"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "722b54f9f1bd4f09a1f09af25cd656e7"

# Durable Objects for counters
[[durable_objects.bindings]]
name = "POST_COUNTERS"
class_name = "PostCounter"

[[durable_objects.bindings]]
name = "FLICK_COUNTERS"
class_name = "FlickCounter"

[[durable_objects.bindings]]
name = "VIEWER_TRACKER"
class_name = "ViewerTracker"

# Migrations
[[migrations]]
tag = "v1"
new_classes = ["PostCounter"]

[[migrations]]
tag = "v2"
new_classes = ["FlickCounter", "ViewerTracker"]