name = "aniflixx-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
AUTH_WORKER_URL = "https://aniflixx-auth.workers.dev"
MEDIA_WORKER_URL = "https://aniflixx-media.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "aniflixx-main-db"
database_id = "2b5513fe-cf8c-4bb5-8872-5e85c38d5e54"

[[kv_namespaces]]
binding = "CACHE"
id = "213dae65137c472ba25b69159b3ca570"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "722b54f9f1bd4f09a1f09af25cd656e7"

[[ durable_objects.bindings ]]
name = "POST_COUNTERS"
class_name = "PostCounter"

[[migrations]]
tag = "v1"
new_classes = ["PostCounter"]